spring:
  profiles:
    active: development

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/employeesystem
    username: employeesystem
    password: employeesystem123
    testWhileIdle: true
    time-between-eviction-runs-millis: 3600000
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: vrahic@i4di.org
    password: ejwdjkkwpzmbubvv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  cache:
    cache-names: assignment_app
  servlet:
    multipart:
      max-file-size: 10MB

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

